spring.application.name=beta2

spring.datasource.url=jdbc:postgresql://localhost/techfix_beta2
spring.datasource.username=postgres
spring.datasource.password=123456

spring.web.error.include-stacktrace=never
