
create table marcas(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_marca varchar(100) not null
);

create table departamentos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_departamento varchar(40) not null
);

create table categorias(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_categoria varchar(40) not null,
    id_departamento bigint,

    CONSTRAINT fk_categoria_departamento
        FOREIGN KEY (id_departamento)
        REFERENCES departamentos(id)
);

create table subcategorias(
    id bigint generated by default as identity primary key,
    nome_subcategoria varchar(40) not null,
    id_departamento bigint,
    id_categoria bigint,

    CONSTRAINT fk_subcategoria_departamento
        FOREIGN KEY (id_departamento)
        REFERENCES departamentos(id),

    CONSTRAINT fk_subcategoria_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categorias(id)
);

create table pessoas(
    id bigint generated by default as identity primary key,
    nome varchar(1000) not null,
    razao_social varchar(1000) not null,
    cpf_cnpj varchar(14) not null,
    email varchar(255) not null,
    nacimento_funcacao date not null,
    telefone_titular varchar(14) not null,
    nome_segunda_pessoa varchar(1000),
    telefone_segunda_pessoa varchar(14),
    cliente boolean,
    funcionario boolean,
    fornecedor boolean,
    site_fornecedor varchar(1000),
    logradouro varchar(255) not null,
    numero varchar(10),
    bairro varchar(255) not null,
    complemento varchar(255),
    cidade varchar(255) not null,
    uf varchar(2) not null,
    cep varchar(8) not null
);

create table garantias(
    id bigint generated by default as identity primary key,
    id_fornecedor bigint,
    detalhes_garantia varchar(500),
    tempo_garantia integer,

    constraint fk_garantia_fornecedor
        foreign key (id_fornecedor)
        references pessoas(id)
);

create table unidades_medidas(
    id bigint generated by default as identity primary key,
    codigo varchar(3) not null,
    descricao varchar(40) not null,
    multiplicador integer
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(40) NOT NULL,
    descricao_comercial VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    id_marca BIGINT NOT NULL,
    id_departamento BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    id_subcategoria BIGINT NOT NULL,
    id_fornecedor BIGINT NOT NULL,
    margem DOUBLE PRECISION,
    custo_medio NUMERIC(12,4),
    preco_venda NUMERIC(12,4),
    preco_sugestao NUMERIC(12,4),
    minimo INTEGER,
    maximo INTEGER,
    id_garantia BIGINT,
    id_unidade_medida BIGINT,
    ativo BOOLEAN,
    foto VARCHAR(1000),


    CONSTRAINT fk_produto_marca
        FOREIGN KEY (id_marca)
        REFERENCES marcas(id),

    CONSTRAINT fk_produto_departamento
        FOREIGN KEY (id_departamento)
        REFERENCES departamentos(id),

    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categorias(id),

    CONSTRAINT fk_produto_subcategoria
        FOREIGN KEY (id_subcategoria)
        REFERENCES subcategorias(id),

    CONSTRAINT fk_produto_fornecedor
        FOREIGN KEY (id_fornecedor)
        REFERENCES pessoas(id),

    CONSTRAINT fk_produto_garantia
        FOREIGN KEY (id_garantia)
        REFERENCES garantias(id),

    CONSTRAINT fk_produto_unidade_medida
        FOREIGN KEY (id_unidade_medida)
        REFERENCES unidades_medidas(id)

);

create table estoques(
    id bigint generated by default as identity primary key,
    id_produto bigint,
    estoque_contabil integer,
    saldo_ordem_servico integer,
    saldo_pedido_venda integer,
    saldo_trocas integer,

    constraint fk_estoque_produto
        foreign key (id_produto)
        references produtos(id)
);

create table compatibilidade(
    id bigint generated by default as identity primary key,
    id_produto bigint not null,
    compativel varchar(255) not null,

    constraint fk_compatibilidade_produto
        foreign key (id_produto)
            references produtos(id)
);

create table usuarios(
    id bigint generated by default as identity primary key,
    nome_usuario varchar(255) not null unique,
    id_pessoa bigint not null,
    funcao varchar(255) not null,
    ativo boolean,

    constraint fk_usuario_pessoa
        foreign key (id_pessoa)
        references pessoas(id)
);

create table formas_pagamento(
    id_fpg bigint generated by default as identity primary key,
    descricao_fpg varchar(255) not null
);

create table tabelas_descontos(
    id bigint generated by default as identity primary key,
    nome_usuario varchar(255),
    id_departamento bigint,
    id_categoria bigint,
    id_subcategoria bigint,
    id_fpg bigint,
    id_produto bigint,
    desconto numeric(2, 4),

    constraint fk_desconto_usuario
        foreign key (nome_usuario)
        references usuarios(nome_usuario),

    constraint fk_desconto_departamento
        foreign key (id_departamento)
        references departamentos(id),

    constraint fk_desconto_categoria
        foreign key (id_categoria)
        references categorias(id),

    constraint fk_desconto_subcategoria
        foreign key (id_subcategoria)
        references subcategorias(id),

    constraint fk_desconto_fpg
        foreign key (id_fpg)
        references formas_pagamento(id_fpg),

    constraint fk_desconto_produto
        foreign key (id_produto)
        references produtos(id)
);

CREATE TABLE ordens_servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    data_entrada TIMESTAMP NOT NULL,
    aparelho_cliente VARCHAR(255) NOT NULL,
    problema_relatado VARCHAR(1000) NOT NULL,
    acessorios_cliente VARCHAR(255),
    atendente_recebeu VARCHAR(255) NOT NULL,
    tecnico_responsavel VARCHAR(255),
    diagnostico_tecnico VARCHAR(1000),
    diagnostico_igual_relato BOOLEAN,
    statusos VARCHAR(30) NOT NULL,
    testes_realizados VARCHAR(255),
    cpf_retirante VARCHAR(20),
    nome_retirante VARCHAR(255),

    CONSTRAINT fk_os_id_pessoas
        FOREIGN KEY (pessoa_id)
        REFERENCES pessoas(id)
);

CREATE TABLE orcamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id BIGINT NOT NULL,
    numero_item INTEGER NOT NULL,
    id_produto BIGINT,
    descricao VARCHAR(255),
    quantidade INTEGER,
    preco_peca NUMERIC(12,4),
    preco_mao_obra NUMERIC(12,4),
    status_item_orcamento VARCHAR(30) NOT NULL,
    observacoes VARCHAR(1000),

    CONSTRAINT fk_orcamento_id_os
        FOREIGN KEY (ordem_servico_id)
            REFERENCES ordens_servicos(id),

    CONSTRAINT uk_orcamento_item
        UNIQUE (ordem_servico_id, numero_item)
);

create table vendas_cabecalho(
     id bigint generated by default as identity primary key,
     numero_nota bigint,
     id_pessoa bigint,
     data_venda timestamp,
     nome_usuario varchar(255),
     id_od bigint,

     constraint fk_venda_cabecalho_pessoa
         foreign key (id_pessoa)
             references pessoas(id),

     constraint fk_venda_cabecalho_usuario
         foreign key (nome_usuario)
             references usuarios(nome_usuario),

     constraint fk_venda_cabecalho_os
         foreign key (id_od)
             references ordens_servicos(id)
);

create table vendas_corpo(
     id bigint generated by default as identity primary key,
     id_venda_cabecalho bigint,
     numero_item integer,
     id_produto bigint,
     quantidade integer,
     preco_venda NUMERIC(12,4),
     valor_desconto NUMERIC(12,4),
     percentual_desconto numeric(2, 4),
     custo_medio_venda NUMERIC(12,4),
     margem_venda float,

     constraint fk_venda_corpo_venda_cabecalho
         foreign key (id_venda_cabecalho)
             references vendas_cabecalho(id),

     constraint fk_venda_corpo_produto
         foreign key (id_produto)
             references produtos(id)
);

create table tipos_movimentacoes(
    codigo_movimentacao bigint primary key,
    descricao_movimentacao varchar(50),
    operacao varchar(20),
    acrecenta_diminui integer
);

create table movimentacoes_mercadorias(
    id bigint generated by default as identity primary key,
    data_movimentacao timestamp,
    id_tipo_movimentacao bigint,
    quantidade integer,
    custo_unitario numeric(12, 4),
    custo_total numeric(12, 4),
    custo_unitario_medio numeric(12, 4),

    constraint fk_movimentacao_mercadoria_tipo_movimentacao
        foreign key (id_tipo_movimentacao)
        references tipos_movimentacoes(codigo_movimentacao)
);

create table aparelhos(
    id bigint generated by default as identity primary key,
    id_produto bigint,
    tipo_aparelho varchar(255),
    condicao_aparelho varchar(255),
    especificacoes jsonb,
    imei varchar(50),
    observacoes varchar(255),
    pecas_trocadas varchar(1000),
    status_conservacao varchar(255),

    constraint fk_aparelho_produto
        foreign key (id_produto)
        references produtos(id)
);

create table requisicoes_cabecalho(
    id bigint generated by default as identity primary key,
    id_os bigint,
    nome_usuario varchar(20),
    data_criacao timestamp,
    ativo boolean,
    id_fornecedor bigint,

    constraint fk_requisicao_cabecalho_ordem_servico
        foreign key (id_os)
        references ordens_servicos(id),

    constraint fk_requisicao_cabecalho_usuario
        foreign key (nome_usuario)
        references usuarios(nome_usuario),

    constraint fk_requisicao_cabecalho_fornecedor
        foreign key (id_fornecedor)
        references pessoas(id)
);

create table requisicoes_corpo(
    id bigint generated by default as identity primary key,
    id_requisicao_cabecalho bigint,
    numero_item integer,
    id_produto bigint,
    descricao varchar(40),
    quantidade integer,
    status_req varchar(30),
    data_entrega date,
    preco_pretendido numeric(12,4),

    constraint fk_requisicao_corpo_requisicao_cabecalho
        foreign key (id_requisicao_cabecalho)
        references requisicoes_cabecalho(id),

    constraint fk_requisicoes_corpo_produto
        foreign key (id_produto)
        references produtos(id)

);

create table pedidos_cabecalho(
    id bigint generated by default as identity primary key,
    id_requisicao_cabecalho bigint,
    nome_usuario varchar(20),
    data_criacao timestamp,
    ativo boolean,
    id_fornecedor bigint,
    id_fpg bigint,
    prazo_pagamento int,

    constraint fk_pedido_cabecalho_requisicao_cabecalho
        foreign key (id_requisicao_cabecalho)
        references requisicoes_cabecalho(id),

    constraint fk_pedido_cabecalho_usuario
        foreign key (nome_usuario)
        references usuarios(nome_usuario),

    constraint fk_pedido_cabecalho_fornecedor
        foreign key (id_fornecedor)
        references pessoas(id),

    constraint fk_pedido_cabecalho_fpg
        foreign key (id_fpg)
        references formas_pagamento(id_fpg)
);

create table pedidos_corpo(
    id bigint generated by default as identity primary key,
    id_pedido_cabecalho bigint,
    numero_item integer,
    id_produto bigint,
    quantidade integer,
    status_req varchar(30),
    data_entrega date,
    preco_compra numeric(12, 4),

    constraint fk_pedido_corpo_pedido_cabecalho
        foreign key (id_pedido_cabecalho)
        references pedidos_cabecalho(id),

    constraint fk_pedido_corpo_produto
        foreign key (id_produto)
        references produtos(id)

);

create table entradas_notas_fiscais_cabecalho(
    id bigint generated by default as identity primary key,
    numero_nota bigint,
    destinatario varchar(255),
    chave_nota varchar(40),
    id_fornecedor bigint,
    frete numeric(12, 4),

    constraint fk_entradas_cabecalho_pessoa
        foreign key (id_fornecedor)
        references pessoas(id)
);

create table entradas_notas_fiscal_corpo(
    id bigint generated by default as identity primary key,
    id_nota_cabecalho bigint,
    id_produto bigint,
    quantidade integer,
    preco_compra numeric(12, 4),
    id_pedido_corpo bigint,

    constraint fk_entrada_corpo_entrada_cabecalho
        foreign key (id_nota_cabecalho)
        references entradas_notas_fiscais_cabecalho(id),

    constraint fk_entrada_corpo_produto
        foreign key (id_produto)
        references produtos(id),

    constraint fk_entrada_corpo_pedido_corpo
        foreign key (id_pedido_corpo)
        references pedidos_corpo(id)
);

create table contas_receber(
    id bigint generated by default as identity primary key,
    id_venda_cabecalho bigint,
    id_fpg bigint,
    numero_parcela integer,
    valor_parcela numeric(12, 4),
    vencimento date,
    status_parcela varchar(10),

    constraint fk_contas_receber_venda_cabecalho
        foreign key (id_venda_cabecalho)
        references vendas_cabecalho(id),

    constraint fk_contas_receber_fpg
        foreign key (id_fpg)
        references formas_pagamento(id_fpg)
);

create table contas_pagar(
    id bigint generated by default as identity primary key,
    id_entrada_cabecalho bigint,
    id_fpg bigint,
    numero_parcela integer,
    valor_parcela numeric(12, 4),
    vencimento date,
    status_parcela varchar(10),

    constraint fk_contas_receber_entrada_cabecalho
        foreign key (id_entrada_cabecalho)
        references entradas_notas_fiscais_cabecalho(id),

    constraint fk_contas_receber_fpg
        foreign key (id_fpg)
        references formas_pagamento(id_fpg)
)