create table aparelhos_clientes(
    id bigint generated by default as identity primary key,
    id_produto bigint,
    tipo_aparelho varchar(255),
    especificacoes jsonb,
    imei varchar(50),
    id_pessoa bigint,

    constraint fk_aparelho_cliente_produto
        foreign key (id_produto)
        references produtos(id),

    constraint fk_aparelho_cliente_pessoa
        foreign key (id_pessoa)
        references pessoas(id)
);

alter table ordens_servicos
rename column pessoa_id to id_pessoa;

alter table ordens_servicos
alter column aparelho_cliente type bigint
using aparelho_cliente::bigint;

alter table ordens_servicos
add constraint fk_os_aparelho_cliente
      foreign key (aparelho_cliente)
      references aparelhos_clientes(id)

