create table dias_condicoes_pagamento(
    id bigint generated by default as identity primary key,
    id_condicao bigint,
    dias integer,

    constraint fk_dias_condicoes_pagamento
                                     foreign key (id_condicao)
                                     references condicoes_pagamento(id)
)